# Generated by Django 5.1.7 on 2025-08-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('CS', 'Computer Science'), ('DS', 'Design')], max_length=2)),
                ('main_image', models.ImageField(help_text='Primary thumbnail image for the project.', upload_to='project_images/main/')),
                ('category', models.CharField(blank=True, choices=[('ui-ux', 'UI/UX Design'), ('branding', 'Branding'), ('illustration', 'Illustration'), ('other', 'Other')], max_length=20, null=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated list of tech used, e.g., "React, Django, PostgreSQL"', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='A short summary of the project.', null=True)),
                ('problem_statement', models.TextField(blank=True, help_text='What was the core problem this project aimed to solve?', null=True)),
                ('my_role', models.CharField(blank=True, help_text='e.g., Lead Developer, UI/UX Designer', max_length=200, null=True)),
                ('key_challenges', models.TextField(blank=True, help_text='What were the main technical or design challenges?', null=True)),
                ('learnings', models.TextField(blank=True, help_text='What key skills or lessons did you take away?', null=True)),
                ('project_url', models.URLField(blank=True, help_text='Link to the live project if available.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='project_videos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(help_text='e.g., Project Manager at TechCorp', max_length=100)),
                ('project_related', models.ForeignKey(blank=True, help_text='Optional: Link to a specific project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
            ],
        ),
    ]
