# Generated by Django 5.1.7 on 2025-07-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_challenges',
            field=models.TextField(blank=True, help_text='What were the main technical or design challenges?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='learnings',
            field=models.TextField(blank=True, help_text='What key skills or lessons did you take away?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='my_role',
            field=models.CharField(blank=True, help_text='e.g., Lead Developer, UI/UX Designer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='What was the core problem this project aimed to solve?', null=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(help_text='e.g., Project Manager at TechCorp', max_length=100)),
                ('project_related', models.ForeignKey(blank=True, help_text='Optional: Link to a specific project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
            ],
        ),
    ]
