# Generated by Django 5.1.7 on 2025-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectimage_projectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('ui-ux', 'UI/UX Design'), ('branding', 'Branding'), ('illustration', 'Illustration'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
